version: "3.8"

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name:  landing_php
        restart: unless-stopped
        volumes:
            - .:/landing
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - laravel

    db:
        image: mysql:8
        container_name:  landing_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name:  landing_nginx
        restart: unless-stopped
        ports:
            - "88:80"
        volumes:
            - .:/landing
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - php

networks:
    laravel:

volumes:
    db_data:
